#!/usr/bin/env ruby

require 'rubygems'
require 'json'
require 'open-uri'
require 'nokogiri'
require_relative 'cq_common'
require_relative 'cq_configuration'

module Cq
  module Clean

    # Get all keys from hash recursively
    def self.nested_keys(hash)
      keys = []
      hash.keys.each { |key|
        if hash[key].is_a? Hash
          keys += nested_keys(hash[key])
        end
        keys << key
      }
      keys
    end

    def self.exec

      config = ConfigurationReader.new
      clean_config = config.active_project.config.clean_config

      verbose = config.is_debug?
      server = config.active_server
      user = server.user
      pass = server.pass
      nodes = clean_config.nodes

      # Find packages to remove based on bundle patterns
      bundles = []
      pkg_xml = Nokogiri::XML(open("#{server.url}/crx/packmgr/service.jsp?cmd=ls", :http_basic_authentication => [user, pass]).read)
      pkg_xml.xpath('//package').each {|package|
        name = (package > 'name/text()').text
        group = (package > 'group/text()').text
        download_name = (package > 'downloadName/text()').text
        clean_config.bundles.each {|bundle|
          if name.eql? bundle['name'] and group.eql? bundle['group']
            # Use the download name to spec the file when interacting with the service later
            bundle['name'] = download_name
            bundles.push(bundle) 
          end 
        }
      }

      puts '=-=-=-=-=-=-=-=-=-=-=-=-=-=-='
      puts 'Nodes to delete:'
      puts '=-=-=-=-=-=-=-=-=-=-=-=-=-=-='
      puts nodes
      puts ''
      puts '=-=-=-=-=-=-=-=-=-=-=-=-=-=-='
      puts 'Bundles to delete:'
      puts '=-=-=-=-=-=-=-=-=-=-=-=-=-=-='
      puts bundles
      puts ''
      puts 'Continue (y/n)?'

      yn = gets.chomp
      if yn !~ /[y|yes]/i
        puts 'Quiting'
        exit
      end

      v = ''
      if verbose
        v = '-v'
      end

      # Remove the packages
      commands = %w(uninstall delete)
      bundles.each { |bundle|
        group = bundle['group']
        name = bundle['name']
        path = (group.nil? || group.empty?) ? "#{name}" : "#{group}/#{name}"
        commands.each { |cmd|
          `curl #{v} -X POST -H 'referer: app:/' -u #{user}:#{pass} -F cmd=#{cmd} #{server.url}/crx/packmgr/service/script.html/etc/packages/#{path}`
        }
      }

      # Remove the nodes
      nodes.each { |path|
        `curl #{v} -H 'referer: app:/' -F":operation=delete" #{server.url}#{path} -u #{user}:#{pass}`
      }

      puts 'Done'
    end

  end
end

Cq::Clean::exec
