#!/bin/sh

mvn archetype:generate \
-DarchetypeCatalog=http://dev.cqblueprints.com/nexus/content/repositories/releases/ \
-Dfilter=multi-module \
-DartifactId=$1 \
-Dproject-name=$1 \
-DcqDependencyVersion=5.5.0