#!/usr/bin/env ruby

require_relative 'cq_configuration_setter'

module CqTools
  module SetServer
    ConfigurationSetter::exec_switch 'workspace', 'workspaces' do |server|
      ConfigurationSetter::write_env 'CQ_TOOLS_WORKSPACE', server['path']
      ConfigurationSetter::reload_env
    end
  end
end