#!/usr/bin/env ruby

require_relative 'cq_configuration_setter'

include CqTools::ConfigurationSetter

exec_switch 'workspace', 'workspaces' do |branch|
    write_env 'CQ_TOOLS_WORKSPACE', branch['path']
end